from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
        migrations.CreateModel(name='Category',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=100)),('slug',models.SlugField(unique=True))]),
        migrations.CreateModel(name='Customer',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=150)),('email',models.EmailField(blank=True,max_length=254)),('phone',models.CharField(blank=True,max_length=30)),('address',models.CharField(blank=True,max_length=255)),('credit_enabled',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name='Product',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=180)),('slug',models.SlugField(unique=True)),('description',models.TextField(blank=True)),('price',models.DecimalField(decimal_places=2,max_digits=10)),('cost',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('stock',models.PositiveIntegerField(default=0)),('image',models.ImageField(blank=True,null=True,upload_to='products/')),('active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('category',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='products',to='store.category'))]),
        migrations.CreateModel(name='Order',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(choices=[('pending','Pendente'),('paid','Pago'),('delivered','Entregue'),('cancelled','Cancelado')],default='pending',max_length=20)),('payment_method',models.CharField(choices=[('cash','À vista'),('credit','Conta do cliente')],default='cash',max_length=20)),('due_date',models.DateField(blank=True,null=True)),('total',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('created_at',models.DateTimeField(default=django.utils.timezone.now)),('customer',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='orders',to='store.customer'))]),
        migrations.CreateModel(name='OrderItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity',models.PositiveIntegerField(default=1)),('unit_price',models.DecimalField(decimal_places=2,max_digits=10)),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='store.order')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='store.product'))]),
        migrations.CreateModel(name='Payment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('amount',models.DecimalField(decimal_places=2,max_digits=10)),('method',models.CharField(choices=[('cash','Dinheiro'),('pix','PIX'),('card','Cartão'),('transfer','Transferência')],default='cash',max_length=20)),('paid_at',models.DateTimeField(default=django.utils.timezone.now)),('note',models.CharField(blank=True,max_length=180)),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='payments',to='store.order'))]),
        migrations.CreateModel(name='FinancialEntry',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('type',models.CharField(choices=[('income','Receita'),('expense','Despesa'),('investment','Investimento')],max_length=20)),('description',models.CharField(max_length=180)),('amount',models.DecimalField(decimal_places=2,max_digits=12)),('date',models.DateField(default=django.utils.timezone.now)),('order',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='store.order')),('payment',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='store.payment'))]),
    ]
